# Generated by Django 4.2.5 on 2023-10-12 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_alter_customuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('house_name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('pin_code', models.IntegerField()),
                ('occupation', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('rationcard_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.DecimalField(decimal_places=0, max_digits=10)),
                ('acc_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=20)),
                ('subdistrict', models.CharField(max_length=50)),
                ('panchayath', models.CharField(max_length=50)),
                ('ward_no', models.IntegerField()),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='societies', to='farm.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='IFSCcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankname', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('accno', models.IntegerField()),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ifsc_codes', to='farm.farmer')),
            ],
        ),
        migrations.AddField(
            model_name='farmer',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmers', to='farm.society'),
        ),
    ]
