# Generated by Django 4.2.5 on 2023-10-15 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0007_alter_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
